"""add_is_published_to_outbox

Revision ID: 3fd7dec413d6
Revises: 1d00b6a687c0
Create Date: 2026-07-05 22:32:44.250286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd7dec413d6'
down_revision: Union[str, Sequence[str], None] = '1d00b6a687c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox', sa.Column('is_published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox', 'is_published')
    # ### end Alembic commands ###
